# This is the main build configuration block.
[build]
  # A simple build command to ensure the process runs.
  command = "echo 'Build command running...'"
  # Explicitly define the directory for your website's public files.
  publish = "."
  # Explicitly define the functions directory within the build context.
  functions = "netlify/functions"

# This is a separate, top-level functions configuration block.
# While it seems redundant, this explicitness helps resolve pathing issues.
[functions]
  directory = "netlify/functions"
